version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "wsgi.py"
      FLASK_ENV: "development"
      DATABASE_URL: "postgresql://postgres:password@db:5432/app_db"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
